language: node_js
node_js:
  - "node"
script:
  -
deploy:
  provider: firebase
  token:
    secure: "1//0dRlSW5ApCBUSCgYIARAAGA0SNwF-L9IruxI0lOZpVdU9gVwADSLSEFFa4gTNXmqHERfGxdhCQo4VABW6hJBW0RYIgInTZ7jFZaI"

