language: node_js
node_js: 8

before_script:
  - npm install firebase-tools -g
  - cd functions && npm install

script:
  - firebase deploy --only hosting,functions --token "BnzK...rTI="

branches:
  only:
    - master

#language: node_js
#node_js:
#  - "8.1.2"
#branches:
#  only:
#    - master
#script:
#  - npm install -g firebase-tools
#after_success:
#  - firebase deploy --token $FIREBASE_TOKEN --non-interactive



#node_js:
#  - "7"
#script:
# - echo "Deploy!!"
#install:
#  - npm install -g firebase-tools
#after_success:
#  - firebase deploy --project $PROJECT_ID --token "1//0dRlSW5ApCBUSCgYIARAAGA0SNwF-L9IruxI0lOZpVdU9gVwADSLSEFFa4gTNXmqHERfGxdhCQo4VABW6hJBW0RYIgInTZ7jFZaI"
