language: node_js
node_js:
  - "node"

deploy:
  provider: firebase
  token:
    secure: $FIREBASE_TOKEN
#node_js:
#  - "7"
#script:
# - echo "Deploy!!"
#install:
#  - npm install -g firebase-tools
#after_success:
#  - firebase deploy --project $PROJECT_ID --token "1//0dRlSW5ApCBUSCgYIARAAGA0SNwF-L9IruxI0lOZpVdU9gVwADSLSEFFa4gTNXmqHERfGxdhCQo4VABW6hJBW0RYIgInTZ7jFZaI"
